import Header from '@/components/Header'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Providers from '@/components/Providers'
import { cn } from '@/lib/utils'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  authModal
}: {
  children: React.ReactNode
  authModal: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
        <body className={cn("antialiased min-h-screen bg-slate-50", inter.className)}>
          <Providers>
            <Header/>
            {authModal}

            <main className='container max-w-7xl mx-auto h-full pt-8'>
              {children}
            </main>
          </Providers>
        </body>
    </html>
  )
}
